### PR TITLE
Iterative (chunked) input processing

### PR DESCRIPTION
**Pull request by pesco**
I think I accidentally picked the hardest backend to add this to first, but alas. Adds three new functions to the Hammer API and implements them for the LL(k) backend:
```
HSuspendedParser* h_parse_start(const HParser* parser);  // has __m variant
bool h_parse_chunk(HSuspendedParser* s, const uint8_t* input, size_t length);
HParseResult* h_parse_finish(HSuspendedParser* s);
```

In addition, this branch contains a few tidbits that aren't strictly speaking part of chunking:
* Made it so that tests no longer silently "succeed" when `h_compile` fails. This exposed the `int_range` test on regex not compiling (not implemented). I disabled the test.
* Changed my weird use of a single-byte allocation for a dummy address to just use `((void *)-1)` as an unused pointer value besides NULL. I think that's OK, right?
* Noticed that none of the context-free backends set the parse result's `bit_length`. Added tests and fixed it.

### CODE REVIEW

**Comment by thequux** [comment]
I won't be able to look at this properly until tomorrow, but I can respond to the miscellaneous changes now; the first and third are awesome, but I'd actually prefer to define MARK as

    static const void* MARK = &MARK;

The reason is that the various allocators are defined to behave like the POSIX allocators, which return (void*)-1 on error. This means that, if there is badly-behaved code that doesn't check the return values of the system allocator, those values could be transparently misinterpreted as MARK.

**Comment by pesco** [comment]
Ah, good point! I didn't catch that. I also didn't think of using its own address for the pointer; d'oh!

**Comment by pesco** [comment]
> the various allocators are defined to behave like the POSIX allocators, which return (void*)-1 on error.

Actually, though, I can't find any reference to this behavior. Are we talking about `malloc`? Are there any relevant systems that actually do this?

I ask because I used `(void *)-1` to signal `NEED_INPUT` from `h_stringmap_get_lookahead` and in this case I am concerned about the caller mistaking the dummy value for a valid result. I'd like `NEED_INPUT` to segfault when dereferenced.

**Comment by uucidl** [comment]
:+1: for the goal of this pull request :)

**Comment by uucidl** [comment]
I see that the latest build failed on appveyor. I'm looking into it, I do not know what they have changed and why but the standard library header files aren't found anymore.

**Comment by uucidl** [comment]
I found a reference to this issue: https://github.com/appveyor/ci/issues/414

**Comment by uucidl** [comment]
Created a PR with a fix: https://github.com/UpstandingHackers/hammer/pull/145

**Comment by abiggerhammer** [comment]
Merged. Is there a way to check this PR with appveyor again before merging it?

**Comment by uucidl** [comment]
Unfortunately I think it needs to be rebased or the commit has to be appveyor commit has to be cherry-picked into it to test it

**Comment by nil-ableton** [comment]
Actually you can retrigger the Appveyor job for this pull request now, since they have removed the need for the workaround.

**Comment by abiggerhammer** [comment]
Thanks for the tip, @nil-ableton. Merged, and thanks, @pesco!

**Pull request merged**
