### PR TITLE
Some combinators may report the wrong amount of consumed input

### PR DESCRIPTION
**Pull request by pesco**
Commit af73181c changed it so that `perform_lowlevel_parse` only recalculates the result's `bit_length` if it was set to 0. At least the `h_bind` combinator as well as the `h_left`/`h_right` family of combinators relied on the old behavior. There may be others.

### CODE REVIEW

**Comment by pesco** [comment]
Ping on this PR, @thequux @abiggerhammer .

**Comment by pesco** [comment]
As far as I can tell both the above test failures are bogus. Travis barfs on an outdated PHP version and AppVeyor doesn't like our internal use of `#include "../..."`.

If there are no objections, I'm going to merge this change but leave the ticket open, because somebody (maybe me when I find time) should go through the combinators to make sure they all report the proper `bit_length` (in the Packrat backend).

**Comment by uucidl** [comment]
For the AppVeyor build, you should just disable this warning C4464.
You can do so by looking at

https://github.com/UpstandingHackers/hammer/blob/master/tools/windows/clvars.bat

And just add a -wd4464 to disable this warning

**Comment by pesco** [comment]
Cool, thanks!

**Comment by pesco** [comment]
Cf. #158. The Travis problem seems to have since solved itself.

**Comment by abiggerhammer** [comment]
Thanks, and apologies for the delay in reviewing. Working from the road is hard :(

**Pull request merged**
